export interface NewsArticle {
  id?: string; // Optional: as it's usually generated by the database
  title: string;
  text: string;
  imageUrl: string; // Can be an empty string if no image
  isFeatured: boolean;
  // createdAt and updatedAt are typically managed by the database
  // createdAt?: string; 
  // updatedAt?: string;
}
