export interface NewsArticle {
  id?: string; // Optional: as it's usually generated by the database
  title: string;
  text: string;
  imageUrl: string; // Can be an empty string if no image, or placeholder, or actual URL
  isFeatured: boolean;
  createdAt?: string; // Usually managed by Supabase (timestamp with timezone)
  updatedAt?: string; // Usually managed by Supabase (timestamp with timezone)
}
